### ISSUE TITLE
amount está dando erro com variável no blade

### ISSUE THREAD

**Issue by frankjardel** [flyingluscas/pagarme-laravel#7]
Olá,

Estou obtendo um erro ao tentar usar variável..

Estou tentando da seguinte maneira:

@checkout([
...
    'amount' => "{{ number_format($total, 2,'','') }}",
...
])

minha pergunta é: como adiciono valor dinamico nesse parametro?

Desde já agradeço qualquer ajuda :)

**Comment by frankjardel** [comment]
Resolvi substituindo o @checkout por:

<form action="/payment" method="post">
	<script type="text/javascript" src="https://assets.pagar.me/checkout/checkout.js"
		data-encryption-key="ek_test_cKbN..."
		data-button-text="Finalizar Compra"
		data-amount="{{ number_format($total, 2,'','') }}"
		data-customer-data="true"
		data-payment-methods="boleto,credit_card"
		data-ui-color="#bababa"
		data-postback-url="requestb.in/1234"
		data-create-token="true"
		data-interest-rate="12"
		data-free-installments="10"
		data-default-installment="5"
		data-header-text=""
		data-checkout-id="0">
	</script>
</form>

**Comment by flyingluscas** [comment]
@frankjardel Consegue dar mais detalhes sobre o erro?

**Comment by frankjardel** [comment]
@flyingluscas Agradeço por responder eu consegui resolver substituindo o template por código javascript :)
